VER_MAJOR = 1
VER_MINOR = 1.0
INSTALL_INC = libmysqlwrapped.h myparam_comm.h
SRCS = ./Database.cpp ./Query.cpp ./enum_t.cpp ./example.cpp ./myparam_comm.cpp ./set_t.cpp

INCLS = ./Database.h ./IError.h ./Query.h ./enum_t.h ./libmysqlwrapped.h ./myparam_comm.h ./set_t.h

INCLUDE = -I. -I/usr/include/mtagent_api_open -I/usr/include/my_proto -I/usr/include/Sockets -I/usr/include/mtreport_api
